version: "3.9"

services:
  mystoredb:
    image: postgres:14.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: MyStoreDb
    # ports:
      # - "5433:5432"
    volumes:
      - database:/var/lib/postgresql/data
    restart: always

  mystoreback:
    build: 
      context: ./MyStoreBack
      dockerfile: Dockerfile
    depends_on:
      - mystoredb
    ports:
      # - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
        - MyStoreImages:/app/Uploads
        - /home/ssl/:/home/ssl/
    restart: always

    

volumes:
  database:
  MyStoreImages:
